# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from module import MathCalculate
"""from main2 import Ui_Max_Intake_Intensity_Window
from main3 import Ui_Maximum_Voltage_Drop_Window
from main4 import Ui_Shortcircuit_Window"""


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(504, 184)
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        MainWindow.setMinimumSize(600, 600)
        palette = QtGui.QPalette()
        palette.setColor(QtGui.QPalette.Window, QtGui.QColor(173, 216, 230))
        palette.setColor(QtGui.QPalette.WindowText, QtGui.QColor(0, 0, 0))
        palette.setColor(QtGui.QPalette.Button, QtGui.QColor(70, 130, 180))
        palette.setColor(QtGui.QPalette.ButtonText, QtGui.QColor(255, 255, 255))
        palette.setColor(QtGui.QPalette.Base, QtGui.QColor(255, 255, 255))
        palette.setColor(QtGui.QPalette.Text, QtGui.QColor(0, 0, 0))

        MainWindow.setPalette(palette)
        button_style = """
        QPushButton {
            background-color: #4682B4;
            color: black;
            border: 2px solid #4682B4;
            border-radius: 5px;
            font-size: 12px;
            padding: 2px 15px;
        }
        QPushButton:hover {
            background-color: #1E90FF;
            border: 2px solid #1E90FF;
        }
        QPushButton:pressed {
            background-color: #4169E1;
            border: 2px solid #4169E1;
        }
        """

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.maxintakeintenbtn = QtWidgets.QPushButton(self.centralwidget)
        self.maxintakeintenbtn.setGeometry(QtCore.QRect(20, 30, 381, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.maxintakeintenbtn.setFont(font)
        self.maxintakeintenbtn.setObjectName("maxintakeintenbtn")
        self.maxvoltdropbtn = QtWidgets.QPushButton(self.centralwidget)
        self.maxvoltdropbtn.setGeometry(QtCore.QRect(20, 60, 381, 21))
        self.maxvoltdropbtn.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.maxvoltdropbtn.setFont(font)
        self.maxvoltdropbtn.setObjectName("maxvoltdropbtn")
        self.shortcircuit = QtWidgets.QPushButton(self.centralwidget)
        self.shortcircuit.setGeometry(QtCore.QRect(20, 90, 211, 23))
        self.shortcircuit.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.shortcircuit.setFont(font)
        self.shortcircuit.setObjectName("shortcircuit")
        self.selectionlabel = QtWidgets.QLabel(self.centralwidget)
        self.selectionlabel.setGeometry(QtCore.QRect(10, 0, 481, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.selectionlabel.setFont(font)
        self.selectionlabel.setObjectName("selectionlabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.maxintakeintenbtn = QtWidgets.QPushButton(self.centralwidget)
        self.maxintakeintenbtn.setGeometry(QtCore.QRect(20, 30, 381, 23))
        self.maxintakeintenbtn.setStyleSheet(button_style)

        self.maxvoltdropbtn = QtWidgets.QPushButton(self.centralwidget)
        self.maxvoltdropbtn.setGeometry(QtCore.QRect(20, 60, 381, 21))
        self.maxvoltdropbtn.setStyleSheet(button_style)

        self.shortcircuit = QtWidgets.QPushButton(self.centralwidget)
        self.shortcircuit.setGeometry(QtCore.QRect(20, 90, 211, 23))
        self.shortcircuit.setStyleSheet(button_style)

        self.maxintakeintenbtn.clicked.connect(self.open_max_intake_window)
        self.maxvoltdropbtn.clicked.connect(self.open_max_volt_drop)
        self.shortcircuit.clicked.connect(self.open_short_circuit_window)
        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.maxintakeintenbtn, self.maxvoltdropbtn)
        MainWindow.setTabOrder(self.maxvoltdropbtn, self.shortcircuit)

    def open_max_intake_window(self):
        self.maxintakewindow = QtWidgets.QMainWindow()
        self.ui = Ui_Max_Intake_Intensity_Window()
        self.ui.setupUi(self.maxintakewindow)
        self.maxintakewindow.show()

    def open_max_volt_drop(self):
        self.maxvoltdropwindow = QtWidgets.QMainWindow()
        self.ui = Ui_Maximum_Voltage_Drop_Window()
        self.ui.setupUi(self.maxvoltdropwindow)
        self.maxvoltdropwindow.show()

    def open_short_circuit_window(self):
        self.shortcuitwindow = QtWidgets.QMainWindow()
        self.ui = Ui_Shortcircuit_Window()
        self.ui.setupUi(self.shortcuitwindow)
        self.shortcuitwindow.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.maxintakeintenbtn.setText(_translate(
            "MainWindow", "Intensidad máxima admisible/Maximum Intake Intensity."))
        self.maxvoltdropbtn.setText(_translate(
            "MainWindow", "Caída máxima de Tensión/Maximum Voltage Drop."))
        self.shortcircuit.setText(_translate(
            "MainWindow", "Cortocircuito/ Short Circuit"))
        self.selectionlabel.setText(_translate(
            "MainWindow", "Calculo de Secciones Eléctricas/Calculation of Electrical Cross-Sections"))

######################################################################


class Ui_Max_Intake_Intensity_Window(object):
    def setupUi(self, max_intake_window):
        max_intake_window.setObjectName("max_intake_window")
        max_intake_window.resize(629, 351)
        self.centralwidget = QtWidgets.QWidget(max_intake_window)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.firstvalue = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.firstvalue.setFont(font)
        self.firstvalue.setObjectName("firstvalue")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.firstvalue)
        self.inputfirstval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputfirstval.setObjectName("inputfirstval")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.inputfirstval)
        self.secondvalue = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.secondvalue.setFont(font)
        self.secondvalue.setObjectName("secondvalue")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.secondvalue)
        self.inputsecondval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputsecondval.setObjectName("inputsecondval")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.inputsecondval)
        self.thirdvalue = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.thirdvalue.setFont(font)
        self.thirdvalue.setObjectName("thirdvalue")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.thirdvalue)
        self.inputthirdval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputthirdval.setObjectName("inputthirdval")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.LabelRole, self.inputthirdval)
        self.fourthvalue = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fourthvalue.setFont(font)
        self.fourthvalue.setObjectName("fourthvalue")
        self.formLayout.setWidget(
            6, QtWidgets.QFormLayout.LabelRole, self.fourthvalue)
        self.inputfourthval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputfourthval.setObjectName("inputfourthval")
        self.formLayout.setWidget(
            7, QtWidgets.QFormLayout.LabelRole, self.inputfourthval)
        self.fifthvalue = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fifthvalue.setFont(font)
        self.fifthvalue.setObjectName("fifthvalue")
        self.formLayout.setWidget(
            8, QtWidgets.QFormLayout.LabelRole, self.fifthvalue)
        self.inputfifthval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputfifthval.setObjectName("inputfifthval")
        self.formLayout.setWidget(
            9, QtWidgets.QFormLayout.LabelRole, self.inputfifthval)
        self.calculatebtn = QtWidgets.QPushButton(self.centralwidget)
        self.calculatebtn.setObjectName("calculatebtn")
        self.formLayout.setWidget(
            10, QtWidgets.QFormLayout.SpanningRole, self.calculatebtn)
        max_intake_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(max_intake_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 21))
        self.menubar.setObjectName("menubar")
        max_intake_window.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(max_intake_window)
        self.statusBar.setObjectName("statusBar")
        max_intake_window.setStatusBar(self.statusBar)

        self.objectmath = MathCalculate()
        self.calculatebtn.clicked.connect(self.f_max_intake)

        self.retranslateUi(max_intake_window)
        QtCore.QMetaObject.connectSlotsByName(max_intake_window)

    def f_max_intake(self,):
        self.objectmath.function_calculation_maximum_admissible_intensity(
            self.inputfirstval,
            self.inputsecondval,
            self.inputthirdval,
            self.inputfourthval,
            self.inputfifthval
        )

    def retranslateUi(self, max_intake_window):
        _translate = QtCore.QCoreApplication.translate
        max_intake_window.setWindowTitle(_translate(
            "MAX INTAKE INTENSITY", "MAX INTAKE INTENSITY"))
        self.firstvalue.setText(_translate(
            "SecondWindow", "Valor de la resistividad en [ohm mm2/m] / Resistivity value in [ohm mm²/m]"))
        self.secondvalue.setText(_translate(
            "SecondWindow", "Valor de la longitud en [m] / Length value in [m]"))
        self.thirdvalue.setText(_translate(
            "SecondWindow", "Valor de la seccion en [mm2]] / Sectional value in [mm2]"))
        self.fourthvalue.setText(_translate(
            "SecondWindow", "Valor del tiempo de funcionamiento del equipo en [s] / Operating time value of the equipment in [s]"))
        self.fifthvalue.setText(_translate(
            "SecondWindow", "Valor de consumo aproximado del receptor en [A] / Approximate consumption value of the receiver in [A]"))
        self.calculatebtn.setText(_translate(
            "SecondWindow", "Calcular/ Calculate"))


######################################################################
class Ui_Maximum_Voltage_Drop_Window(object):
    def setupUi(self, MaxVoltDrop):
        MaxVoltDrop.setObjectName("MaxVoltDrop")
        MaxVoltDrop.resize(594, 511)
        self.centralwidget = QtWidgets.QWidget(MaxVoltDrop)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.firstval = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.firstval.setFont(font)
        self.firstval.setObjectName("firstval")
        self.verticalLayout.addWidget(self.firstval)
        self.inputfirstval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputfirstval.setObjectName("inputfirstval")
        self.verticalLayout.addWidget(self.inputfirstval)
        self.secondval = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.secondval.setFont(font)
        self.secondval.setObjectName("secondval")
        self.verticalLayout.addWidget(self.secondval)
        self.inputsecondval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputsecondval.setObjectName("inputsecondval")
        self.verticalLayout.addWidget(self.inputsecondval)
        self.thirdval = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.thirdval.setFont(font)
        self.thirdval.setObjectName("thirdval")
        self.verticalLayout.addWidget(self.thirdval)
        self.inputthirdval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputthirdval.setObjectName("inputthirdval")
        self.verticalLayout.addWidget(self.inputthirdval)

        self.fourthval = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fourthval.setFont(font)
        self.fourthval.setObjectName("fourthval")
        self.verticalLayout.addWidget(self.fourthval)
        self.inputfourthval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputfourthval.setObjectName("inputfourthval")
        self.verticalLayout.addWidget(self.inputfourthval)

        self.fifthval = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fifthval.setFont(font)
        self.fifthval.setObjectName("fifthval")
        self.verticalLayout.addWidget(self.fifthval)
        self.inputfifthval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputfifthval.setObjectName("fifthval")
        self.verticalLayout.addWidget(self.inputfifthval)

        self.threephasebtn = QtWidgets.QPushButton(self.centralwidget)
        self.threephasebtn.setObjectName("threephasebtn")
        self.verticalLayout.addWidget(self.threephasebtn)
        self.onephasebtn = QtWidgets.QPushButton(self.centralwidget)
        self.onephasebtn.setObjectName("onephasebtn")
        self.verticalLayout.addWidget(self.onephasebtn)
        MaxVoltDrop.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MaxVoltDrop)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 594, 21))
        self.menubar.setObjectName("menubar")
        MaxVoltDrop.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MaxVoltDrop)
        self.statusbar.setObjectName("statusbar")
        MaxVoltDrop.setStatusBar(self.statusbar)

        self.retranslateUi(MaxVoltDrop)
        QtCore.QMetaObject.connectSlotsByName(MaxVoltDrop)

        self.objectmath = MathCalculate()
        self.onephasebtn.clicked.connect(self.f_drop_volt1)
        self.threephasebtn.clicked.connect(self.f_drop_volt3)

    def f_drop_volt1(self,):
        self.objectmath.function_calculation_singlephase_voltage_drop(
            self.inputfirstval,
            self.inputsecondval,
            self.inputthirdval,
            self.inputfourthval,
            self.inputfifthval
        )

    def f_drop_volt3(self,):
        self.objectmath.function_calculation_threephase_voltage_drop(
            self.inputfirstval,
            self.inputsecondval,
            self.inputthirdval,
            self.inputfourthval,
            self.inputfifthval
        )

    def retranslateUi(self, MaxVoltDrop):
        _translate = QtCore.QCoreApplication.translate
        MaxVoltDrop.setWindowTitle(_translate(
            "MAX VOLT DROP", "MAX VOLT DROP"))
        self.firstval.setText(_translate(
            "MainWindow", "Valor de la potencia en [W] / Power value in [W]"))
        self.secondval.setText(_translate(
            "MainWindow", "Valor de la longitud en [m] / Length value in [m]"))
        self.thirdval.setText(_translate(
            "MainWindow", "Valor de la conductividad en [m/ohm mm2] / Conductivity value in [m/ohm mm2]"))
        self.fourthval.setText(_translate(
            "MainWindow", "Valor de caida de tension en [V] / Voltage drop value in [V]"))
        self.fifthval.setText(_translate(
            "MainWindow", "Valor de tension de linea en [V] / Line voltage value in [V]"))
        self.threephasebtn.setText(_translate(
            "MainWindow", "Cálculo caída de tensión trifásica / Calculate three-phase voltage drop."))
        self.onephasebtn.setText(_translate(
            "MainWindow", "Cálculo caída de tensión monofásica / Calculate single-phase voltage drop."))
######################################################################


class Ui_Shortcircuit_Window(object):
    def setupUi(self, Shortcircuit):
        Shortcircuit.setObjectName("Shortcircuit")
        Shortcircuit.resize(610, 300)
        self.centralwidget = QtWidgets.QWidget(Shortcircuit)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.firstvalue = QtWidgets.QLabel(self.centralwidget)

        font = QtGui.QFont()
        font.setPointSize(10)
        self.firstvalue.setFont(font)
        self.firstvalue.setObjectName("firstvalue")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.firstvalue)
        self.inputfirstval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputfirstval.setObjectName("inputfirstval")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.inputfirstval)
        self.secondvalue = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.secondvalue.setFont(font)
        self.secondvalue.setObjectName("secondvalue")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.secondvalue)
        self.inputsecondval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputsecondval.setObjectName("inputsecondval")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.inputsecondval)
        self.thirdvalue = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.thirdvalue.setFont(font)
        self.thirdvalue.setObjectName("thirdvalue")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.thirdvalue)
        self.inputthirdval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputthirdval.setObjectName("inputthirdval")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.LabelRole, self.inputthirdval)
        self.fourthvalue = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fourthvalue.setFont(font)
        self.fourthvalue.setObjectName("fourthvalue")
        self.formLayout.setWidget(
            6, QtWidgets.QFormLayout.LabelRole, self.fourthvalue)
        self.inputfourthval = QtWidgets.QLineEdit(self.centralwidget)
        self.inputfourthval.setObjectName("inputfourthval")
        self.formLayout.setWidget(
            7, QtWidgets.QFormLayout.LabelRole, self.inputfourthval)
        self.calculatebtn = QtWidgets.QPushButton(self.centralwidget)
        self.calculatebtn.setObjectName("calculatebtn")
        self.formLayout.setWidget(
            8, QtWidgets.QFormLayout.SpanningRole, self.calculatebtn)
        Shortcircuit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Shortcircuit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 21))
        self.menubar.setObjectName("menubar")
        Shortcircuit.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(Shortcircuit)
        self.statusBar.setObjectName("statusBar")
        Shortcircuit.setStatusBar(self.statusBar)

        self.retranslateUi(Shortcircuit)
        QtCore.QMetaObject.connectSlotsByName(Shortcircuit)

        self.objectmath = MathCalculate()
        self.calculatebtn.clicked.connect(self.f_short_circuit)

    def f_short_circuit(self,):
        self.objectmath.function_shortcircuit(
            self.inputfirstval,
            self.inputsecondval,
            self.inputthirdval,
            self.inputfourthval,
        )

    def retranslateUi(self, Shortcircuit):
        _translate = QtCore.QCoreApplication.translate
        Shortcircuit.setWindowTitle(_translate("SHORTCIRCUIT", "SHORTCIRCUIT"))
        self.firstvalue.setText(_translate(
            "Shortcircuit", "Valor de la longitud en [m] / \"Length value in [m]"))
        self.secondvalue.setText(_translate(
            "Shortcircuit", "Valor de resistividad del conductor en[ohm mm2/m] / Conductor resistivity value in [ohm mm2/m]"))
        self.thirdvalue.setText(_translate(
            "Shortcircuit", "Valor de la seccion en [mm2] / Section value in [mm2]"))
        self.fourthvalue.setText(_translate(
            "Shortcircuit", "Valor de tension de la red en [V] / Network voltage value in [V]"))
        self.calculatebtn.setText(_translate(
            "Shortcircuit", "Calcular / Calculate"))
